### ISSUE TITLE
Super Mario 64 DS OpenGL Issue

### ISSUE THREAD

**Issue by Peduls** [Arisotura/melonDS#1031]
Koopa appears incorrectly when using OpenGL.
![Software](https://user-images.githubusercontent.com/34750422/110741866-9e218e00-81f2-11eb-9281-224cfeef7468.PNG)
![OpenGL](https://user-images.githubusercontent.com/34750422/110741877-a24dab80-81f2-11eb-95df-a4ff33beff29.PNG)

**Comment by Arisotura** [comment]
prolly side-effects of upscaling graphics meant for a 256x192 screen. except for the weird triangle at the top, that one would be worth looking into.

**Comment by RSDuck** [comment]
was this made with 0.9.1 or a previous version. It might be a regression which has already been fixed.

**Comment by Digifiend84** [comment]
The screenshots say melonDS 0.9.1 at the top. Considering that Arisotura (the emulator's developer) responded just before you did, RSDuck, it clearly hasn't been fixed.

**Comment by RSDuck** [comment]
there were some OpenGL regressions it melonDS 0.9.1 which I fixed afterwards (they're included in 0.9.2). It's possible that the question's author was using a build from latest source (which would say 0.9.1 in the title bar as well).

**Comment by Peduls** [comment]
> 
> 
> there were some OpenGL regressions in melonDS 0.9.1 which I fixed afterwards (they're included in 0.9.2). It's possible that the issue's author was using a build from latest source (which would say 0.9.1 in the title bar as well), where those fixes would have been already included.

This is correct.

**Comment by Peduls** [comment]
Issue is still present in 0.9.2
![Capture](https://user-images.githubusercontent.com/34750422/128111075-90c507f2-3efa-481a-aa3c-b95c16c3362a.PNG)

**Comment by Peduls** [comment]
> 
> 
> prolly side-effects of upscaling graphics meant for a 256x192 screen. except for the weird triangle at the top, that one would be worth looking into.

The same issue can be seen at native resolution when using OpenGL.
![Capture](https://user-images.githubusercontent.com/34750422/128111462-6d79623d-071c-4136-ab4d-e7608baba06d.PNG)
