### ISSUE TITLE
SaGa3: Very heavy flickering when using OpenGL renderer

### ISSUE THREAD

**Issue by dogtopus** [Arisotura/melonDS#957]
melonDS commit: cd6859ef6f449f3f61db312addea9d656069736e

Title screen rendered by OpenGL renderer (a lot of solid polygons flickering. Not only title screen has this problem)

![Screenshot from 2021-01-22 04-28-43](https://user-images.githubusercontent.com/3405234/105466355-7d18d400-5c6a-11eb-9e24-4d250115f7df.png)

Title screen rendered by software renderer (what it should look like)

![Screenshot from 2021-01-22 04-28-58](https://user-images.githubusercontent.com/3405234/105466469-a3d70a80-5c6a-11eb-83a2-5aa15f5f32e5.png)

**Comment by RSDuck** [comment]
can you try again with the latest revision. We just fixed a regression in the OGL renderer.

**Comment by dogtopus** [comment]
> can you try again with the latest revision? We just fixed a regression in the OGL renderer.

Still the same on latest revision. In fact I recall that this issue was always there since the very early days of OpenGL renderer so I doubt it's just some regressions.

**Comment by poudink** [comment]
![SaGa 3 OpenGL](https://user-images.githubusercontent.com/29778535/105649422-369bc300-5e7e-11eb-83f2-f8758b5273c6.png)
Cannot reproduce with either the latest commit or the commit mentioned in the first post.

**Comment by RSDuck** [comment]
it looks a bit similar to the the issue with w buffering which I experienced on linux as well (but not on windows) with an intel hd 4000).

**Comment by dogtopus** [comment]
> it looks a bit similar to the the issue with w buffering which I experienced on linux as well (but not on windows) with an intel hd 4000).

Mine is HD4000 as well. Maybe it's an issue specific to Intel graphics given that some people can't reproduce it.

**Comment by poudink** [comment]
Can confirm that I am using Windows.

**Comment by dogtopus** [comment]
I no longer have the hardware to reproduce this issue. Besides that it's pretty clear that this is likely a driver bug in the Intel HD Graphics 4000 as I wasn't able to reproduce this anywhere else. Therefore I'm closing this. If someone found the root cause and/or have a fix, feel free to reopen it.
